"""Base emitter ABC for harnessctl."""

from __future__ import annotations

import difflib
import logging
import os
import tempfile
from abc import ABC
from pathlib import Path

import jinja2

from harnessctl.render.context import build_context
from harnessctl.render.engine import RenderEngine
from harnessctl.spec.models import Spec

logger = logging.getLogger(__name__)

GENERATED_MARKER = "# GENERATED by harnessctl — do not edit"


class Emitter(ABC):
    """Abstract base class for harness-specific emitters.

    Subclasses must implement :meth:`emit_file` to write a single rendered
    artifact to a resolved target path.  The base class provides helpers for
    safe writes (atomic move, backup of non-generated files, generated
    markers) and the four emit modes.
    """

    HARNESS_ID: str = ""

    @staticmethod
    def _prepend_marker(content: str) -> str:
        """Return *content* with the generated marker prepended."""
        return f"{GENERATED_MARKER}\n{content}"

    @staticmethod
    def _has_marker(text: str) -> bool:
        """Return whether *text* contains the generated marker."""
        return GENERATED_MARKER in text

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        """Write *content* to *path* atomically via a temporary file."""
        fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
        except Exception:
            os.close(fd)
            raise
        os.replace(tmp, path)

    @staticmethod
    def _backup_if_needed(path: Path) -> None:
        """Back up *path* to ``*.bak`` if it exists and lacks the marker."""
        if not path.exists():
            return
        existing = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            bak = path.with_suffix(path.suffix + ".bak")
            path.rename(bak)

    @staticmethod
    def _unified_diff(existing: str, new: str, path: str) -> str:
        """Return a unified diff of *existing* → *new*."""
        return "\n".join(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                new.splitlines(keepends=True),
                fromfile=path,
                tofile=path,
            )
        )

    def _emit_templates(
        self,
        spec: Spec,
        base_path: str,
        mode: str,
        agent_dir: str,
        skills_dir: str,
    ) -> None:
        """Render and emit agent and skill templates.

        Iterates over ``spec.agents`` and the packaged ``skills`` directory,
        rendering matching Jinja2 templates and emitting them via
        :meth:`emit_file`.

        Args:
            spec: The canonical spec.
            base_path: Resolved target directory path.
            mode: One of ``"dry-run"``, ``"diff"``, ``"check"``, ``"write"``.
            agent_dir: Subdirectory name for emitted agent files.
            skills_dir: Subdirectory name for emitted skill files.
        """
        context = build_context(spec, self.HARNESS_ID)

        template_dirs: list[Path] = []
        packaged = (
            Path(__file__).resolve().parents[2] / "spec" / "defaults" / "templates"
        )
        if packaged.exists():
            template_dirs.append(packaged)

        engine = RenderEngine(template_dirs).bind_spec(spec)

        # --- agents ---
        for name in spec.agents:
            template_name = f"agents/{name}.md.j2"
            try:
                rendered = engine.render(template_name, context)
            except jinja2.exceptions.TemplateNotFound:
                logger.warning("Template not found: %s", template_name)
                continue
            target = Path(base_path) / agent_dir / f"{name}.md"
            self.emit_file(str(target), rendered, mode)

        # --- skills ---
        skills_source = packaged / "skills"
        if skills_source.exists():
            for skill_dir in sorted(skills_source.iterdir()):
                if not skill_dir.is_dir():
                    continue
                skill_name = skill_dir.name
                template_name = f"skills/{skill_name}/SKILL.md.j2"
                try:
                    rendered = engine.render(template_name, context)
                except jinja2.exceptions.TemplateNotFound:
                    logger.warning("Template not found: %s", template_name)
                    continue
                target = Path(base_path) / skills_dir / skill_name / "SKILL.md"
                self.emit_file(str(target), rendered, mode)

    def _write_content_with_mode(
        self, path: Path, new_content: str, existing_content: str, mode: str
    ) -> None:
        """Helper to handle the four modes of writing content."""
        if mode == "dry-run":
            return
        if mode == "diff":
            if existing_content != new_content:
                diff = self._unified_diff(existing_content, new_content, str(path))
                raise FileChangedError(str(path), diff)
            return
        if mode == "check":
            if existing_content != new_content:
                diff = self._unified_diff(existing_content, new_content, str(path))
                raise FileChangedError(str(path), diff)
            return
        if mode == "write":
            self._backup_if_needed(path)
            path.parent.mkdir(parents=True, exist_ok=True)
            self._atomic_write(path, new_content)
            return
        raise ValueError(f"Unknown mode: {mode!r}")

    def emit_file(self, target_path: str, content: str, mode: str) -> None:
        """Emit *content* to *target_path* using the given *mode*."""
        path = Path(target_path)
        full_content = self._prepend_marker(content)
        existing_content = ""
        if path.exists():
            existing_content = path.read_text(encoding="utf-8")
        elif mode == "check" or mode == "diff":
            # If diff/check and it doesn't exist, we treat it as empty
            # Wait, check mode for a missing file raised an error originally
            if mode == "check":
                raise FileChangedError(
                    target_path, f"File {target_path!r} does not exist."
                )
            # If diff mode, we just diff against empty
            pass

        self._write_content_with_mode(path, full_content, existing_content, mode)


class FileChangedError(Exception):
    """Raised when a ``check`` mode detects drift."""

    def __init__(self, path: str, diff: str) -> None:
        self.path = path
        self.diff = diff
        super().__init__(f"File {path!r} has drift.\n{diff}")
