"""Base emitter ABC for harnessctl."""

from __future__ import annotations

import difflib
import os
import tempfile
from abc import ABC, abstractmethod
from pathlib import Path

GENERATED_MARKER = "# GENERATED by harnessctl — do not edit"


class Emitter(ABC):
    """Abstract base class for harness-specific emitters.

    Subclasses must implement :meth:`emit_file` to write a single rendered
    artifact to a resolved target path.  The base class provides helpers for
    safe writes (atomic move, backup of non-generated files, generated
    markers) and the four emit modes.
    """

    @abstractmethod
    def emit_file(self, target_path: str, content: str, mode: str) -> None:
        """Emit *content* to *target_path* using the given *mode*.

        Args:
            target_path: Absolute path where the file should be written.
            content: Rendered file content (without the generated marker;
                the implementation should prepend it when writing).
            mode: One of ``"dry-run"``, ``"diff"``, ``"check"``, ``"write"``.

        Raises:
            ValueError: If *mode* is not recognised.
            FileChangedError: If *mode* is ``"check"`` and the on-disk content
                differs from *content*.
        """

    @staticmethod
    def _prepend_marker(content: str) -> str:
        """Return *content* with the generated marker prepended."""
        return f"{GENERATED_MARKER}\n{content}"

    @staticmethod
    def _has_marker(text: str) -> bool:
        """Return whether *text* contains the generated marker."""
        return GENERATED_MARKER in text

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        """Write *content* to *path* atomically via a temporary file."""
        fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
        except Exception:
            os.close(fd)
            raise
        os.replace(tmp, path)

    @staticmethod
    def _backup_if_needed(path: Path) -> None:
        """Back up *path* to ``*.bak`` if it exists and lacks the marker."""
        if not path.exists():
            return
        existing = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            bak = path.with_suffix(path.suffix + ".bak")
            path.rename(bak)

    @staticmethod
    def _unified_diff(existing: str, new: str, path: str) -> str:
        """Return a unified diff of *existing* → *new*."""
        return "\n".join(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                new.splitlines(keepends=True),
                fromfile=path,
                tofile=path,
            )
        )


class FileChangedError(Exception):
    """Raised when a ``check`` mode detects drift."""

    def __init__(self, path: str, diff: str) -> None:
        self.path = path
        self.diff = diff
        super().__init__(f"File {path!r} has drift.\n{diff}")
